import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { BarChart3, Brain, Code } from "lucide-react";
import React from "react";

function Features() {
  return (
    <section
      id="features"
      className="w-full py-12 md:py-24 lg:py-32 bg-muted/50"
    >
      <div className="px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              Features
            </h2>
            <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Everything you need to prepare for your next coding interview
            </p>
          </div>
        </div>
        <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 mt-8">
          <Card>
            <CardHeader>
              <Brain className="h-10 w-10 mb-2" />
              <CardTitle>AI-Generated Questions</CardTitle>
              <CardDescription>
                Practice with unique MCQs and coding challenges generated by AI
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p>
                Our AI creates questions that match real interview patterns from
                top tech companies.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <Code className="h-10 w-10 mb-2" />
              <CardTitle>Instant Evaluation</CardTitle>
              <CardDescription>
                Get immediate feedback on your code solutions
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p>
                Our AI evaluates your code for correctness, efficiency, and best
                practices in real-time.
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <BarChart3 className="h-10 w-10 mb-2" />
              <CardTitle>Performance Insights</CardTitle>
              <CardDescription>
                Track your progress with detailed analytics
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p>
                Visualize your strengths and weaknesses across different topics
                and question types.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}

export default Features;
